name: Olivade
favicon: null
layout_spectrum: 0.71754
typography_spectrum: 0.88857
title: "Villa Olivade  – St Paul De Vence – Côte d'Azur"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#82afc6'
    - '#040404'
    - '#b8d7dc'
    - '#7c6c53'
    - '#385700'
  brandStrength: 0.4375
  lightness: 0.625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
